/* Copyright (c) 2017 Arm Limited. All rights reserved.
   SPDX-License-Identifier: BSL-1.0

  Boost Software License - Version 1.0 - August 17th, 2003

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to do
  so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer, must
  be included in all copies of the Software, in whole or in part, and all
  derivative works of the Software, unless such copies or derivative works are
  solely in the form of machine-executable object code generated by a source
  language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
  ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.  */

#include "speculation_barrier.h"
#define NULL ((void*)0)

unsigned char a8[] = { 1, 2, 3, 4, 5, 6, 7, 8 };
unsigned short a16[] = { 1, 2, 3, 4, 5, 6, 7, 8 };
unsigned int a32[] = { 1, 2, 3, 4, 5, 6, 7, 8 };
unsigned long long a64[] = { 1, 2, 3, 4, 5, 6, 7, 8 };

#define test(type, size)						\
int									\
foo_ ## size (type *in)							\
{									\
  type out[13];								\
  type failval = 13;							\
  out[0] = in[3];							\
  __asm__ volatile ("" : : : "memory" );				\
  out[1] = load_no_speculate (in + 3, in, in + 8);			\
  __asm__ volatile ("" : : : "memory" );				\
  out[2] = load_no_speculate_fail (in + 3, in, in + 8, failval);	\
  __asm__ volatile ("" : : : "memory" );				\
  out[3] = load_no_speculate_cmp (in + 3, in, in + 8,			\
				     failval, in + 3);			\
  __asm__ volatile ("" : : : "memory" );				\
  /* Condition check fails cases.  */					\
  out[4] = load_no_speculate (in + 15, in, in + 8);			\
  __asm__ volatile ("" : : : "memory" );				\
  out[5] = load_no_speculate_fail (in + 15, in, in + 8, failval);	\
  __asm__ volatile ("" : : : "memory" );				\
  out[6] = load_no_speculate_cmp (in + 3, in, in + 8,			\
				  failval, in + 15);			\
  /* Condition check succeeds, but we have a NULL lower bound.  */	\
  __asm__ volatile ("" : : : "memory" );				\
  out[7] = load_no_speculate (in + 3, NULL, in + 8);			\
  __asm__ volatile ("" : : : "memory" );				\
  out[8] = load_no_speculate_fail (in + 3, NULL, in + 8, failval);	\
  __asm__ volatile ("" : : : "memory" );				\
  out[9] = load_no_speculate_cmp (in + 3, NULL, in + 8,			\
				     failval, in + 3);			\
  __asm__ volatile ("" : : : "memory" );				\
  out[10] = load_no_speculate (in + 3, in, NULL);			\
  __asm__ volatile ("" : : : "memory" );				\
  out[11] = load_no_speculate_fail (in + 3, in, NULL, failval);		\
  __asm__ volatile ("" : : : "memory" );				\
  out[12] = load_no_speculate_cmp (in + 3, in, NULL,			\
				     failval, in + 3);			\
  __asm__ volatile ("" : : : "memory" );				\
  /* Condition check succeeds, should all be a load of in[3].  */	\
  if (out[0] != in[3])							\
    __builtin_printf ("Failed normal load for size " #size "\n");	\
  if (out[1] != in[3])							\
    __builtin_printf ("Failed 3 operand for size " #size "\n");		\
  if (out[2] != in[3])							\
    __builtin_printf ("Failed 4 operand for size " #size "\n");		\
  if (out[3] != in[3])							\
    __builtin_printf ("Failed 5 operand for size " #size "\n");		\
  /* Condition check fails, should all be a set to failval (which	\
     defaults to zero in the three operand case).  */			\
  if (out[4] != 0)							\
    __builtin_printf ("Failed 3 operand (fail) for size " #size "\n");	\
  if (out[5] != failval)						\
    __builtin_printf ("Failed 4 operand (fail) for size " #size "\n");	\
  if (out[6] != failval)						\
    __builtin_printf ("Failed 5 operand (fail) for size " #size "\n");	\
  /* Condition check succeeds, should all be a load of in[3].  */	\
  if (out[7] != in[3])							\
    __builtin_printf ("Failed 3 operand (NULL lower) for size " #size "\n");	\
  if (out[8] != in[3])							\
    __builtin_printf ("Failed 4 operand (NULL lower) for size " #size "\n");	\
  if (out[9] != in[3])							\
    __builtin_printf ("Failed 5 operand (NULL lower) for size " #size "\n");	\
  if (out[10] != in[3])							\
    __builtin_printf ("Failed 3 operand (NULL upper) for size " #size "\n");	\
  if (out[11] != in[3])							\
    __builtin_printf ("Failed 4 operand (NULL upper) for size " #size "\n");	\
  if (out[12] != in[3])							\
    __builtin_printf ("Failed 5 operand (NULL upper) for size " #size "\n");	\
									\
  return 1;								\
}

test(unsigned char, 8)
test(unsigned short, 16)
test(unsigned int, 32)
test(unsigned long long, 64)

#define check(size)		\
{  foo_ ## size (a ## size); }

int
main (int argc, char** argv)
{
  check (8);
  check (16);
  check (32);
  check (64);
}
